### ISSUE TITLE
FullSync should use the isTrustAllCertificates setting for self-signed HTTPS endpoint

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/c8osdk-android#3]
The setting **trustAllCertificates** works for Convertigo Call and log but FullSync replication failed with SSL errors.

**Comment by nicolas-albert** [comment]
Sample of error:
```
  javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:368)
      at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
      at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
      at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
      at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
      at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
      at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
      at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
      at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
      at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
      at okhttp3.RealCall.getResponse(RealCall.java:243)
      at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
      at okhttp3.RealCall.execute(RealCall.java:57)
      at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:250)
      at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
      at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:762)
```

**Comment by nicolas-albert** [comment]
Fixed by https://github.com/convertigo/c8osdk-android/commit/008ff54adb7218f2fcc7904f1161ae7e0178f173
